config/routes.rb
BsTest::Application.routes.draw do

  resources :events

  root :to => 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html

  def index
    @events = Event.all
    respond_with @events
  end

  def new
    @event = Event.new
    respond_with @event
  end

  def create
    @event = Event.new(params[:event])
    @event.save!
    respond_with @event, :location => events_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event, :html => {:class => 'form-horizontal' }) do |f| %>
    <legend>Event</legend>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :start, :as => :string %>
    <%= f.input :end, :as => :string %>
    <%= f.input :description, :hint => 'Describe the event', :input_html => { :rows => 3 } %>
    <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    </div>
<% end %>

app/views/events/index.html.erb
<script type="text/javascript">
    /* Table initialisation */
    $(document).ready(function() {
        $('#events').dataTable( {
            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            }
        } );
    } );
</script>
<div class="page-header">
<h1>Events</h1>
</div>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="events">
  <thead>
  <tr>
    <th>Name</th>
    <th>Start</th>
    <th>End</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.start %></td>
    <td><%= event.end %></td>
    <td><%= event.description %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<div class="actions">
  <%= link_to 'New Event', new_event_path, :class=>"btn" %>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BsTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<div class="container master-container">
<%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'Events', events_path %>